### PR TITLE
Import ABC from collections.abc instead of collections for Python 3.9 compatibility.

### LINKED ISSUE #7: Importing ABC directly from collections module was removed in Python 3.9
https://bugzilla.redhat.com/show_bug.cgi?id=1792976

https://github.com/sametmax/minibelt/blob/bed47c14abf24216d974a08e50da8ecee516cd00/minibelt.py#L25

Thanks for the library!

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #7

### CODE REVIEW

**Comment by sametmax** [comment]
Are you kidding me ? This lib is used in Fedora ?

I mean, of all the stuff I did in my entire life, minibelt ?

How did that even happened ?

Anyway, I'll merge it ASAP. Thanks for the PR.

**Comment by tirkarthi** [comment]
Thanks for the review and merge :) I am not sure if it's used in Fedora but it's packaged in fedora repo's as per the report.

**Comment by sametmax** [comment]
I added you to the contributors list. TY.

**Comment by tirkarthi** [comment]
Thanks :)

**Pull request merged**
